---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
   - name: install webserver
     apt:
       name: apache2
       state: present
     when: ansible_os_family =="Debian"
   - name: install tree
     apt:
       name: tree
       state: absent
     when: ansible_os_family =="Debian"
   - name: install redhat
     yum:
      name: httpd
      state: present
     when: ansible_os_family =="RedHat" 